extraction:
  javascript:
    index:
      filters:
      - exclude: "src/compiler/JSCodeTemplate.js"
      - exclude: "src/compiler/JSRuntimeTemplate.js"
      - exclude: "src/compiler/JSPureTemplate.js"
