version: 2.1
orbs:
  win: circleci/windows@5.0.0
  codecov: codecov/codecov@3.2.5

executors:
  node18:
    docker:
      - image: cimg/node:18.17

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v5-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build_win:
    executor: win/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - run:
          name: Install NVM
          command: choco install nvm -y
      - run:
          name: Install Node 18.13.0
          shell: bash.exe
          command: |
            nvm list
            nvm install 18.13.0
            nvm use 18.13.0
      - run:
          name: Verify Node Version
          shell: bash.exe
          command: node --version
      - run: npm ci
      - run: mkdir junit
      - run:
          name: Test and Code Coverage
          command: npm run test
          environment:
            MOCHA_FILE: junit/test-results.xml
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

  build:
    executor: node18
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: prepare test git user
          command: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - run:
          name: Test and Code Coverage
          command: npm run test
          environment:
            MOCHA_FILE: junit/test-results.xml
      - codecov/upload
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_win
