version: 2.1
orbs:
  win: circleci/windows-tools@0.1.0

executors:
  node8:
    docker:
    - image: circleci/node:8-jessie
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

commands:
  setup:
    steps:
    - checkout
    - restore_cache:
        keys:
        - v4-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: install npm 6.9.0
        command: sudo npm -g install npm@6.9.0
    - run:
        name: Installing Dependencies
        command: npm install
    - save_cache:
        paths:
        - node_modules
        key: v4-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build_win:
    executor: win/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - run: choco install nodejs
      - run: npm install
      - run: mkdir junit

      # test & get code coverage
      - run:
          name: Test and Code Coverage
          command: npm run test-ci
          environment:
            MOCHA_FILE: junit/test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  build:
    executor: node8

    steps:
    - setup
        # run tests!
    - run: mkdir junit
    - run:
        name: prepare test git user
        command: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

    # test & get code coverage
    - run:
        name: Test and Code Coverage
        command: npm run test-ci
        environment:
          MOCHA_FILE: junit/test-results.xml

    - store_test_results:
        path: junit

    - store_artifacts:
        path: junit

  publish-pre-release:
    executor: node8

    steps:
    - setup
    - run:
        name: revert changes to package-lock.json
        command: git checkout -- package-lock.json

    - run:
        name: configure npm registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

    - run:
        name: Semantic Release
        command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
    # publish pre-releases on master
    - publish-pre-release:
        requires:
        - build
        - build_win
        filters:
          branches:
            only: master
    - build
    - build_win
